spring:
  application:
    name: Campus-Connect
  data:
    mongodb:
      uri: mongodb+srv://campusconnectteamcommon:zOrDZ5F6yUxR98kU@campusconnect.d2vm8.mongodb.net/CampusConnect?retryWrites=true&w=majority&appName=CampusConnect
      auto-index-creation: true
  security:
    user:
      name: user1
      password: password
  app:
    # Secure, base64-encoded 256-bit key for JWT
    jwtSecret: WmGNTUqlB8G6PZAdTezB2xqYfj9k2+qV1J0nFgBrmkI=
    # JWT expiration time in milliseconds
    jwtExpirationMs: 86400000
  main:
    allow-circular-references: true

server:
  port: 8080

# Optional logger configuration
logging:
  level:
    root: INFO
    com.campusconnect.CampusConnect: DEBUG
